#!/bin/sh
set -e

echo "DB_TYPE=$DB_TYPE"
echo "DB_POSTGRESDB_HOST=$DB_POSTGRESDB_HOST"
echo "DB_POSTGRESDB_PORT=$DB_POSTGRESDB_PORT"
echo "DB_POSTGRESDB_DATABASE=$DB_POSTGRESDB_DATABASE"
echo "DB_POSTGRESDB_USER=$DB_POSTGRESDB_USER"
echo "N8N_HOST=$N8N_HOST"
echo "N8N_PORT=$N8N_PORT"
echo "N8N_PROTOCOL=$N8N_PROTOCOL"
echo "WEBHOOK_URL=$WEBHOOK_URL"
echo "N8N_PROXY_HOPS=$N8N_PROXY_HOPS"

exec n8n start
